entrypoints:
  - barista.order.simpleOrder
  - barista.order.latte
  - barista.order.americano
  - barista.order.steamer
applications:
  barista:
    services:
      order:
        operations:
          - name: simpleOrder
            calls:
              - service: brew
                name: dripCoffee
              - application: bakery
                service: order
                name: muffin
            errorChance: 0 # simpleOrder never fails
          - name: latte
            calls:
              - service: brew
                name: espresso
              - service: brew
                name: frothedMilk
              - application: bakery
                service: order
                name: scone
          - name: americano
            calls:
              - service: brew
                name: espresso
          - name: steamer
            calls:
              - service: brew
                name: frothedMilk
      brew:
        operations:
          - name: dripCoffee
            calls:
              - service: fulfillment
                name: pickup
          - name: espresso
            errorChance: 30
            tags:
              _outboundExternalService: AWSLambda
      fulfillment:
        operations: [{ name: delivery }, { name: pickup }]

  bakery:
    services:
      order:
        operations:
          - name: muffin
            calls: [ { application: barista, service: fulfillment, name: delivery } ]
          - name: scone
            calls:
              - application: bakery
                service: oven
                name: warm
                calls: [ { application: barista, service: fulfillment, name: delivery } ]
        tags:
          _outboundExternalService: Redis
